name: Build Midnight Commander

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  prepare_build_enviroment:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-keys:
          - "--without-x"
          - "--disable-shared --enable-static"
    name: Build
    steps:
      - name: Install build dependies
        run: |
          sudo apt update
          sudo apt install  glibc-source \
                            gcc \
                            make \
                            autoconf \
                            automake \
                            libtool \
                            ncurses-base \
                            ncurses-bin \
                            gettext \
                            libssh2-1-dev \
                            libaspell-dev \
                            autopoint \
                            pkg-config \
                            libslang2-dev
    
      - uses: actions/checkout@v3
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: mkdir build && ./configure --prefix=$PWD/build ${{ matrix.build-keys }}
      - name: make
        run: make
      - name: make install
        run: make install
      - name: Set static type variable
        env:
          STATIC: ${{ matrix.build-keys }}
        run: |
          if ${STATIC} == "--without-x"; then
            echo "disttype=distrib" >> $GITHUB_ENV
            echo "Build shared linked binary"
          else
            echo "disttype=static" >> $GITHUB_ENV
            echo "Build static linked binary"
          fi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mc-${{ env.disttype }}
          path: |
            build
#      - name: Archive workflow results
#        uses: actions/upload-artifact@v3
#        with:
#          name: code-workflow-report
#          path: output/test/code-coverage.html



