name: Build Midnight Commander

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  prepare_build_enviroment:
    runs-on: ubuntu-latest
    name: Install build
    steps:
      - name: Install dependies
        run: |
          sudo apt update
          sudo apt install  glibc-source \
                            gcc \
                            make \
                            autoconf \
                            automake \
                            libtool \
                            ncurses-base \
                            ncurses-bin \
                            gettext \
                            libssh2-1-dev \
                            libaspell-dev \
                            autopoint \
                            pkg-config
    
      - uses: actions/checkout@v3
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: mkdir build && ./configure --prefix=$PWD/build
      - name: make
        run: make
      - name: make install
        run: make install

